UniversityRegistrar/Models/Course.cs
using System.Collections.Generic;

namespace UniversityRegistrar.Models
{
  public class Course
  {
    public Course()
    {
      this.JoinEntities = new HashSet<CourseStudent>();
    }

    public int CourseId { get; set; }
    public string CourseName { get; set; }
    public string CourseNumber { get; set; }
    public virtual ICollection<CourseStudent> JoinEntities { get; set; }
  }
}

UniversityRegistrar/Models/CourseStudent.cs
namespace UniversityRegistrar.Models
{
  public class CourseStudent
    {
      public int CourseStudentId { get; set; }
      public int StudentId { get; set; }
      public int CourseId { get; set; }
      public virtual Student Student { get; set; }
      public virtual Course Course { get; set; }
    }
}

UniversityRegistrar/Models/DesignTimeDbContextFactory.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;
using Microsoft.Extensions.Configuration;
using System.IO;

namespace UniversityRegistrar.Models
{
  public class UniversityRegistrarContextFactory : IDesignTimeDbContextFactory<UniversityRegistrarContext>
  {

    UniversityRegistrarContext IDesignTimeDbContextFactory<UniversityRegistrarContext>.CreateDbContext(string[] args)
    {
      IConfigurationRoot configuration = new ConfigurationBuilder()
          .SetBasePath(Directory.GetCurrentDirectory())
          .AddJsonFile("appsettings.json")
          .Build();

      var builder = new DbContextOptionsBuilder<UniversityRegistrarContext>();

      builder.UseMySql(configuration["ConnectionStrings:DefaultConnection"], ServerVersion.AutoDetect(configuration["ConnectionStrings:DefaultConnection"]));

      return new UniversityRegistrarContext(builder.Options);
    }
  }
}

UniversityRegistrar/Models/Student.cs
using System.Collections.Generic;

namespace UniversityRegistrar.Models
{
  public class Student
  {
    public Student()
    {
      this.JoinEntities =new HashSet<CourseStudent>();
    }
    public int StudentId { get; set; }
    public string Name { get; set; }
    public string Enrollment { get; set; }
    public virtual ICollection<CourseStudent> JoinEntities { get; }
  }
}

UniversityRegistrar/Models/UniversityRegistrarContext.cs
using Microsoft.EntityFrameworkCore;

namespace UniversityRegistrar.Models
{
  public class UniversityRegistrarContext : DbContext
  {
    public DbSet<Course> Courses { get; set; }
    public DbSet<Student> Students { get; set; }
    public DbSet<CourseStudent> CourseStudent { get; set; }

    public UniversityRegistrarContext(DbContextOptions options) : base(options) { }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
      optionsBuilder.UseLazyLoadingProxies();
    }
  }
}

UniversityRegistrar/Controllers/CourseController.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using UniversityRegistrar.Models;

namespace UniversityRegistrar.Controllers
{
  public class CoursesController : Controller
  {
    private readonly UniversityRegistrarContext _db;

    public CoursesController(UniversityRegistrarContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Course> model = _db.Courses.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Course course)
    {
      _db.Courses.Add(course);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
        var thisCourse = _db.Courses
            .Include(course => course.JoinEntities)
            .ThenInclude(join => join.Course)
            .FirstOrDefault(course => course.CourseId == id);
        return View(thisCourse);
    }
    public ActionResult Edit(int id)
    {
      var thisCourse = _db.Courses.FirstOrDefault(course => course.CourseId == id);
      return View(thisCourse);
    }

    [HttpPost]
    public ActionResult Edit(Course course)
    {
      _db.Entry(course).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisCourse = _db.Courses.FirstOrDefault(course => course.CourseId == id);
      return View(thisCourse);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisCourse = _db.Courses.FirstOrDefault(course => course.CourseId == id);
      _db.Courses.Remove(thisCourse);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

UniversityRegistrar/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace UniversityRegistrar.Controllers
{
    public class HomeController : Controller
    {

      [HttpGet("/")]
      public ActionResult Index()
      {
        return View();
      }

    }
}

UniversityRegistrar/Controllers/StudentsController.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using UniversityRegistrar.Models;

namespace UniversityRegistrar.Controllers
{
    public class StudentsController : Controller
    {
        private readonly UniversityRegistrarContext _db;

        public StudentsController(UniversityRegistrarContext db)
        {
            _db = db;
        }

        public ActionResult Index()
        {
            return View(_db.Students.ToList());
        }

        public ActionResult Create()
        {
            ViewBag.CourseId =
                new SelectList(_db.Courses, "CourseId", "CourseName");
            return View();
        }

        [HttpPost]
        public ActionResult Create(Student student, int CourseId)
        {
            _db.Students.Add (student);
            _db.SaveChanges();
            if (CourseId != 0)
            {
                _db.CourseStudent.Add(new CourseStudent(){ CourseId = CourseId, StudentId = student.StudentId });
                _db.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        public ActionResult Details(int id)
        {
            var thisStudent = _db.Students
              .Include(student => student.JoinEntities)
              .ThenInclude(join => join.Course)
              .FirstOrDefault(student => student.StudentId == id);
            return View(thisStudent);
        }

        public ActionResult Edit(int id)
        {
            var thisStudent = _db.Students.FirstOrDefault(student => student.StudentId == id);
            ViewBag.CourseId =
                new SelectList(_db.Courses, "CourseId", "CourseName");
            return View(thisStudent);
        }

        [HttpPost]
        public ActionResult Edit(Student student, int CourseId)
        {
            if (CourseId != 0)
            {
                _db.CourseStudent.Add(new CourseStudent(){ CourseId = CourseId, StudentId = student.StudentId });
            }
            _db.Entry(student).State = EntityState.Modified;
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult AddCourse(int id)
        {
            var thisStudent = _db.Students.FirstOrDefault(student => student.StudentId == id);
            ViewBag.CourseId =
                new SelectList(_db.Courses, "CourseId", "Name");
            return View(thisStudent);
        }

        [HttpPost]
        public ActionResult AddCourse(Student student, int CourseId)
        {
            if (CourseId != 0)
            {
                _db.CourseStudent.Add(new CourseStudent() { CourseId = CourseId, StudentId = student.StudentId });
                _db.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
          var thisStudent = _db.Students.FirstOrDefault(student => student.StudentId == id);
          return View(thisStudent);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
          {
            var thisStudent = _db.Students.FirstOrDefault(student => student.StudentId == id);
              _db.Students.Remove(thisStudent);
              _db.SaveChanges();
            return RedirectToAction("Index");
          }

        [HttpPost]
        public ActionResult DeleteCourse(int joinId)
          {
              var joinEntry = _db.CourseStudent.FirstOrDefault(entry => entry.CourseStudentId == joinId);
              _db.CourseStudent.Remove(joinEntry);
              _db.SaveChanges();
              return RedirectToAction("Index");
          }
    }
}

UniversityRegistrar/Views/Courses/Create.cshtml
@{
  Layout = "_Layout";
}

@model UniversityRegistrar.Models.Course

<h4>Add a new course</h4>
@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.CourseName)
  @Html.TextBoxFor(model => model.CourseName)
  @Html.LabelFor(model => model.CourseNumber)
  @Html.TextBoxFor(model => model.CourseNumber)
  <input type="submit" value="Add new course" />
}
<p>@Html.ActionLink("Show all courses", "Index")</p>
<p>@Html.ActionLink("Go back to Home", "Index", "Home")</p>

UniversityRegistrar/Views/Courses/Delete.cshtml
@{
  Layout = "_Layout";
}

@model UniversityRegistrar.Models.Course

<h2>Are you sure you want to delete this?</h2>

@Html.DisplayNameFor(model => model.CourseName): @Html.DisplayFor(model => model.CourseName)
@Html.DisplayFor(model => model.CourseNumber)

@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to List", "Index")
@Html.ActionLink("Back to Home", "Index", "Home")

UniversityRegistrar/Views/Courses/Details.cshtml
@{
  Layout = "_Layout";
}

@model UniversityRegistrar.Models.Course

<h2>Course Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.CourseName): @Html.DisplayFor(model => model.CourseName)<h3>
  <h5>@Html.DisplayNameFor(model => model.CourseNumber): @Html.DisplayFor(model => model.CourseNumber)</h5>

@if(@Model.JoinEntities.Count == 0)
{
  <p>This course does not contain any Students</p>
}
else
{
  <h4>Students in this course contains:</h4>
  <ul>
  @foreach(var join in Model.JoinEntities)
  {
    <li>@join.Student.Name</li>
  }
  </ul>
}

<p>@Html.ActionLink("Back to Courses", "Index")</p> 
<p>@Html.ActionLink("Edit Course", "Edit", new { id = Model.CourseId })</p>
<p>@Html.ActionLink("Delete Course", "Delete", new { id = Model.CourseId })</p>
<p>@Html.ActionLink("Back to Home", "Index", "Home")</p>

UniversityRegistrar/Views/Courses/Edit.cshtml
@{
  Layout = "_Layout";
}

@model UniversityRegistrar.Models.Course

<h2>Edit</h2>

<h4>Edit this course: @Html.DisplayFor(model => model.CourseName)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.CourseId)

  @Html.LabelFor(model => model.CourseName)
  @Html.EditorFor(model => model.CourseName)

  @Html.LabelFor(model => model.CourseNumber)
  @Html.EditorFor(model => model.CourseNumber)

  <input type="submit" value="Save" />
}
<p>@Html.ActionLink("Back to list", "Index")</p>
<p>@Html.ActionLink("Back to Home", "Index", "Home")</p>

UniversityRegistrar/Views/Courses/Index.cshtml
@{
  Layout = "_Layout";
}

@using UniversityRegistrar.Models;

<h1>Courses</h1>

@if (@Model.Count == 0)
{
  <h3>No courses have been added yet!</h3>
} 

<ul>
  @foreach(Course course in Model)
  {
    <li>@Html.ActionLink($"{course.CourseName}", "Details", new { id = course.CourseId })</li>
  }
</ul>

<p>@Html.ActionLink("Add new course", "Create")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

UniversityRegistrar/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}

<h1>Welcome to the UniversityRegistrar!</h1>
<p>@Html.ActionLink("See all students", "Index", "Students")</p>
<p>@Html.ActionLink("See all courses", "Index", "Courses")</p>

UniversityRegistrar/Views/Shared/Footer.cshtml
<div id="footer">Bottom div content</div>

UniversityRegistrar/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>University Registrar!</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/styles.css">
  </head>
  <body>
    @RenderBody()
    @await Html.PartialAsync("Footer")
  </body>
</html>

UniversityRegistrar/Views/Students/AddCourse.cshtml
@{
  Layout = "_Layout";
}

@model UniversityRegistrar.Models.Student

<h2>Add a course</h2>

<h4>Add a course to this task: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.StudentId)

    @Html.Label("Select course")
    @Html.DropDownList("CourseId")

    <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to list", "Index")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

UniversityRegistrar/Views/Students/Create.cshtml
@{
  Layout = "_Layout";
}

@model UniversityRegistrar.Models.Student

<h4>Add a new task</h4>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)

  @Html.LabelFor(model => model.Enrollment)
  @Html.TextBoxFor(model => model.Enrollment)

  @Html.Label("Select course")
  @Html.DropDownList("CourseId")

  <input type="submit" value="Add new student" class="btn btn-default" />
}
<p>@Html.ActionLink("Show all Students", "Index")</p> 

UniversityRegistrar/Views/Students/Delete.cshtml
@{
  Layout = "_Layout";
}

@model UniversityRegistrar.Models.Student

<h2>Are you sure you want to remove this Student?</h2>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
    <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to List", "Index")

UniversityRegistrar/Views/Students/DeleteAll.cshtml
<!-- @* @{
  Layout = "_Layout";
}

@model ToDoList.Models.Item

<h2>Are you sure you want to delete this item?</h2>

@Html.DisplayNameFor(model => model.Description): @Html.DisplayFor(model => model.Description)
@using (Html.BeginForm())
{
    <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to List", "Index") *@ -->

UniversityRegistrar/Views/Students/Details.cshtml
@{
  Layout = "_Layout";
}

@model UniversityRegistrar.Models.Student

<h2>Students Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h3>
<h5>@Html.DisplayNameFor(model => model.Enrollment): @Html.DisplayFor(model => model.Enrollment)</h5>

@if(@Model.JoinEntities.Count == 0)
{
  <p>This item does not belong to any courses</p>
}
else
{
  <h4>Courses the student belongs to:</h4>
  <ul>
  @foreach(var join in Model.JoinEntities)
  {
    <li>@join.Course.CourseName @join.Course.CourseNumber</li>
      
  }
  </ul>
}

<p>@Html.ActionLink("Back to list", "Index")</p>
<p>@Html.ActionLink("Edit Student", "Edit", new { id = Model.StudentId })</p>
<p>@Html.ActionLink("Delete Student", "Delete", new { id = Model.StudentId })</p>
<p>@Html.ActionLink("Go back to Home", "Index", "Home")</p>

UniversityRegistrar/Views/Students/Edit.cshtml
@{
  Layout = "_Layout";
}

@model UniversityRegistrar.Models.Student

<h2>Edit</h2>

<h4>Edit this task: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.StudentId)

    @Html.LabelFor(model => model.Name)
    @Html.EditorFor(model => model.Name)

    @Html.LabelFor(model => model.Enrollment)
    @Html.EditorFor(model => model.Enrollment) 

    @Html.Label("Select course")
    @Html.DropDownList("CourseId") 

    <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to list", "Index")</p>

UniversityRegistrar/Views/Students/index.cshtml
@{
  Layout = "_Layout";
}

@using UniversityRegistrar.Models;
@model List<UniversityRegistrar.Models.Student>;

<h1>Students</h1>

@if (@Model.Count == 0)
{
  <h3>No students have been added yet!</h3>
} 

@foreach (Student student in Model)
{
  <li>@Html.ActionLink($"{student.Name}", "Details", new { id = student.StudentId }) </li>
}

<p>@Html.ActionLink("Add new student", "Create")</p>
<p>@Html.ActionLink("Go back to Home", "Index", "Home")</p>